server:
  port : 8080

logging:
  level:
    org.springframework: INFO
    com.example: TRACE

example:
  url: https://my-json-server.typicode.com/typicode/demo/comments
  filePath: /Users/orkuncavdar/Desktop/comments/comments.txt